/* This class framework is generated by Core Frame Builder. */
/* For more information, refer to http://www.one-lab.net/ */

/* Data Handling Class */
using System;
using System.Text;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.IO;

namespace ns {
public class cls2 : ns.cls, ICloneable {
	public override int GetHashCode() { return base.GetHashCode(); }

	public override bool Equals(object obj) { return this == (cls2)obj; }

	public Int32 mPInt { get; set; }

	public void setPInt(Int32 aPInt) {
		mPInt = aPInt;
	}

	public Int32 getPInt() {
		 return mPInt;
	}

	protected bool compare_to(cls2 aValue) {
		if (!base.compare_to(aValue)) return false;
		if (mPInt != aValue.mPInt) return false;
		return true;
	}

	protected void clone_from(cls2 aValue) {
		base.clone_from(aValue);
		mPInt = aValue.mPInt;
	}

	public new object Clone() {
		cls2 oValue = new cls2();
		oValue.clone_from(this);
		return oValue;
	}

	public static bool operator == (cls2 a0, cls2 a1) { object o1 = (object)a0; object o2 = (object)a1; if (o1 == null && o2 == null) return true; return (o1 == null || o2 == null) ? false : a0.compare_to(a1); }

	public static bool operator != (cls2 a0, cls2 a1) { object o1 = (object)a0; object o2 = (object)a1; if (o1 == null && o2 == null) return false; return (o1 == null || o2 == null) ? true : !a0.compare_to(a1); }

	public cls2(cls2 aValue) { clone_from(aValue); }

	public cls2() {
	}

	public cls2(Int32 aPInt) {
		mPInt = aPInt;
	}

	public void _invoke_(String entry, String input, ref String output) {
		if (false){}
	}
	public virtual int field_count() {
		return base.field_count() + 1;
	}

	private int validate_field(String key, object value) {
		return input_field(key, value, false);
	}

	private int validate_field(int index, object value) {
		return input_field(index, value, false);
	}

	public virtual int input_field(String key, object value, bool _set_value) {
		int result = 0;
		if (base.input_field(key, value, _set_value) == 1) return 1;
		else if (key == "PInt") {
			Int32 v; if (!Int32.TryParse(value.ToString(), out v)) return 0;
			if (_set_value)
				mPInt = v;
			result = 1;
		}
		return result;
	}

	private static readonly string[] field_keys = new string[] { "PInt",  };
	private int input_field(int index, object value, bool _set_value) {
		if (index < 0 || index > (field_count()-1) || value == null) return 0;
		return input_field(field_keys[index], value, _set_value);
	}

	public virtual int to_json(ref String output) {
		String baseOutput = "";
		if (base.to_json(ref baseOutput) == 0) return 0;
		baseOutput = baseOutput.Substring(1, baseOutput.Length-2) + ", ";
		output = "{" + baseOutput + "\"PInt\"" + ":" + "\"" + mPInt.ToString() + "\"" + "}";
		return 1;
	}

	public new int from_json(System.Collections.Hashtable table) {
		SortedList<string, string> list = new SortedList<string, string>();
		foreach (string key in table.Keys) {
			object oValue = table[key];
			if (oValue != null) {
				string value = oValue.ToString();
				if (validate_field(key, value) == 0)
					return 0;
				list.Add(key, value);
			}
		}
		if (list.Count != field_count()) return 0;
		foreach (string k in list.Keys)
			input_field(k, list[k], true);
		return 1;
	}

	public new int from_json(String input) {
		if (string.IsNullOrWhiteSpace(input)) return 0;
		try {
			object obj = json.Parser.Decode(input);
			json.Parser.ParseResult result = (json.Parser.ParseResult)obj;
			return from_json((System.Collections.Hashtable)result.JSONObject);
		}
		catch { return 0; }
	}

	public virtual int to_xml(ref String output, String rowTag) {
		String baseOutput = "";
		if (base.to_xml(ref baseOutput, rowTag) == 0) return 0;
		baseOutput = baseOutput.Replace("<" + rowTag + ">", "").Replace("</" + rowTag + ">", "");
		output = "<" + rowTag + ">" + baseOutput + "<PInt>" + mPInt.ToString().Replace("<", "&lt;").Replace("<", "&gt;") + "</PInt>" + "</" + rowTag + ">";
		return 1;
	}

	public new int from_xml(String input, String rowTag) {
		if (string.IsNullOrWhiteSpace(input) || string.IsNullOrWhiteSpace(rowTag)) return 0;
		try {
			SortedList<string, string> list = new SortedList<string, string>();
			System.Xml.XmlDocument doc = new System.Xml.XmlDocument();
			doc.LoadXml(input);
			if (doc.DocumentElement.Name != rowTag) return 0;
			foreach(System.Xml.XmlNode node in doc.DocumentElement.ChildNodes) {
				string key = node.Name;
				string value = node.InnerText;
				if (validate_field(key, value) == 0) return 0;
				list.Add(key, value);
			}
			if (list.Count != field_count()) return 0;
			foreach (string k in list.Keys)
				input_field(k, list[k], true);
		}
		catch { return 0; }
		return 1;
	}

	public virtual int to_sv(ref String output, String spliter) {
		String baseOutput = "";
		if (base.to_sv(ref baseOutput, spliter) == 0) return 0;
		baseOutput += spliter;
		List<String> list = new List<String>();
		list.Add(mPInt.ToString());
	
		output = baseOutput + String.Join(spliter, list.ToArray());
		return 1;
	}

	public new int from_sv(String input, String spliter) {
		if (string.IsNullOrWhiteSpace(input) || string.IsNullOrWhiteSpace(spliter)) return 0;
		string[] list = input.Split(new string[] { spliter }, StringSplitOptions.RemoveEmptyEntries);
		if (list.Length != field_count()) return 0;
		int index = 0;
		foreach(string item in list)
			if (validate_field(index++, item) == 0)
				return 0;
		index = 0;
		foreach(string item in list)
			input_field(index++, item, true);
		return 1;
	}

}//class cls2
public class cls2List {
	public Object Clone() {
		cls2List obj = new cls2List();
		obj.Items.AddRange(Items);
		return obj;
	}
	public List<cls2> Items = new List<cls2>();

	public override int GetHashCode() { return base.GetHashCode(); }

	public override bool Equals(object obj) { return this == (cls2List)obj; }

	protected bool compare_to(cls2List aValue) {
		if (aValue == null) return false;
		if (Items.Count != aValue.Items.Count) return false;
		for (int n = 0; n < Items.Count; n++) if (Items[n] != aValue.Items[n]) return false;
		return true;
	}

	public static bool operator == (cls2List a0, cls2List a1) { object o1 = (object)a0; object o2 = (object)a1; if (o1 == null && o2 == null) return true; return (o1 == null || o2 == null) ? false : a0.compare_to(a1); }

	public static bool operator != (cls2List a0, cls2List a1) { object o1 = (object)a0; object o2 = (object)a1; if (o1 == null && o2 == null) return false; return (o1 == null || o2 == null) ? true : !a0.compare_to(a1); }

	public int to_json(ref String output, String tag = "cls2") {
		if (string.IsNullOrWhiteSpace(tag)) return 0;
		List<string> list = new List<string>();
		string text = "";
		foreach(cls2 item in Items) {
			item.to_json(ref text);
			list.Add(text);
		}
		output = "{\"" + tag + "\":[" + string.Join(",", list.ToArray()) + "]}";
		return 1;
	}

	public int from_json(String input, String tag = "cls2") {
		if (string.IsNullOrWhiteSpace(input) || string.IsNullOrWhiteSpace(tag)) return 0;
		try {
			List<cls2> newList = new List<cls2>();
			object obj = json.Parser.Decode(input);
			json.Parser.ParseResult result = (json.Parser.ParseResult)obj;
			System.Collections.Hashtable table = (System.Collections.Hashtable)result.JSONObject;
			System.Collections.ArrayList list = (System.Collections.ArrayList)table[tag];
			foreach(object value in list) {
				cls2 cls = new cls2();
				if (cls.from_json((System.Collections.Hashtable)value) == 0) return 0;
				newList.Add(cls);
			}
			Items.Clear();
			Items = newList;
		}
		catch { return 0; }
		return 1;
	}

	public int to_xml(ref String output, String rowTag, String tableTag) {
		if (string.IsNullOrWhiteSpace(rowTag) ||string.IsNullOrWhiteSpace(tableTag)) return 0;
		List<string> list = new List<string>();
		string text = "";
		foreach(cls2 item in Items) {
			item.to_xml(ref text, rowTag);
			list.Add(text);
		}
		output = "<" + tableTag + ">" + string.Join("", list.ToArray()) + "</" + tableTag + ">";
		return 1;
	}

	public int from_xml(String input, String rowTag, String tableTag) {
		if (string.IsNullOrWhiteSpace(input) || string.IsNullOrWhiteSpace(rowTag) || string.IsNullOrWhiteSpace(tableTag)) return 0;
		try {
			List<cls2> newList = new List<cls2>();
			System.Xml.XmlDocument doc = new System.Xml.XmlDocument();
			doc.LoadXml(input);
			if (doc.DocumentElement.Name != tableTag) return 0;
			foreach (System.Xml.XmlNode node in doc.DocumentElement.ChildNodes) {
				cls2 cls = new cls2();
				if (cls.from_xml(node.OuterXml, rowTag) == 0) return 0;
				newList.Add(cls);
			}
			Items.Clear();
			Items = newList;
		}
		catch { return 0; }
		return 1;
	}

	public int to_sv(ref String output, String spliter) {
		if (string.IsNullOrWhiteSpace(spliter)) return 0;
		List<string> list = new List<string>();
		string text = "";
		foreach(cls2 item in Items) {
			item.to_sv(ref text, spliter);
			list.Add(text);
		}
		output = string.Join("\n", list.ToArray());
		return 1;
	}

	public int from_sv(String input, String spliter) {
		if (string.IsNullOrWhiteSpace(input) || string.IsNullOrWhiteSpace(spliter)) return 0;
		string[] list = input.Split(new string[] { "\n" }, StringSplitOptions.RemoveEmptyEntries);
		if (list.Length == 0) return 0;
		List<cls2> newList = new List<cls2>();
		foreach(string item in list) {
			cls2 cls = new cls2();
			if (cls.from_sv(item, spliter) == 0) return 0;
			newList.Add(cls);
		}
		if (newList.Count == list.Length) {
			Items.Clear();
			Items = newList;
			return 1;
		}
		return 0;
	}
}//class cls2List
}//namespace ns