/* This class framework is generated by Core Frame Builder. */
/* For more information, refer to http://www.one-lab.net/ */

/* Data Handling Class */
#ifndef _CLS_H_
#define _CLS_H_

#include "config.h"
#include "values.h"
namespace qtns {
	class cls {
		public:
			virtual bool FuncBool(bool* aArgBool, onelab::Bytes* aArgBytes, QDate* aArgDate, QDateTime* aArgDateTime, double* aArgDouble, float* aArgFloat, int* aArgInt32, QString* aArgText, QTime* aArgTime, unsigned int* aArgUInt32) = 0;
			virtual onelab::Bytes FuncBytes(bool* aArgBool, onelab::Bytes* aArgBytes, QDate* aArgDate, QDateTime* aArgDateTime, double* aArgDouble, float* aArgFloat, int* aArgInt32, QString* aArgText, QTime* aArgTime, unsigned int* aArgUInt32) = 0;
			virtual QDate FuncDate(bool* aArgBool, onelab::Bytes* aArgBytes, QDate* aArgDate, QDateTime* aArgDateTime, double* aArgDouble, float* aArgFloat, int* aArgInt32, QString* aArgText, QTime* aArgTime, unsigned int* aArgUInt32) = 0;
			virtual QDateTime FuncDateTime(bool* aArgBool, onelab::Bytes* aArgBytes, QDate* aArgDate, QDateTime* aArgDateTime, double* aArgDouble, float* aArgFloat, int* aArgInt32, QString* aArgText, QTime* aArgTime, unsigned int* aArgUInt32) = 0;
			virtual double FuncDouble(bool* aArgBool, onelab::Bytes* aArgBytes, QDate* aArgDate, QDateTime* aArgDateTime, double* aArgDouble, float* aArgFloat, int* aArgInt32, QString* aArgText, QTime* aArgTime, unsigned int* aArgUInt32) = 0;
			virtual float FuncFloat(bool* aArgBool, onelab::Bytes* aArgBytes, QDate* aArgDate, QDateTime* aArgDateTime, double* aArgDouble, float* aArgFloat, int* aArgInt32, QString* aArgText, QTime* aArgTime, unsigned int* aArgUInt32) = 0;
			virtual int FuncInt32(bool* aArgBool, onelab::Bytes* aArgBytes, QDate* aArgDate, QDateTime* aArgDateTime, double* aArgDouble, float* aArgFloat, int* aArgInt32, QString* aArgText, QTime* aArgTime, unsigned int* aArgUInt32) = 0;
			virtual QString FuncText(bool* aArgBool, onelab::Bytes* aArgBytes, QDate* aArgDate, QDateTime* aArgDateTime, double* aArgDouble, float* aArgFloat, int* aArgInt32, QString* aArgText, QTime* aArgTime, unsigned int* aArgUInt32) = 0;
			virtual QTime FuncTime(bool* aArgBool, onelab::Bytes* aArgBytes, QDate* aArgDate, QDateTime* aArgDateTime, double* aArgDouble, float* aArgFloat, int* aArgInt32, QString* aArgText, QTime* aArgTime, unsigned int* aArgUInt32) = 0;
			virtual unsigned int FuncUInt32(bool* aArgBool, onelab::Bytes* aArgBytes, QDate* aArgDate, QDateTime* aArgDateTime, double* aArgDouble, float* aArgFloat, int* aArgInt32, QString* aArgText, QTime* aArgTime, unsigned int* aArgUInt32) = 0;
		public:
			void _invoke_(const QString& entry, const QString& input, QString& output);
		};//interface cls
	}//namespace qtns

#endif