/* This class framework is generated by Core Frame Builder. */
/* For more information, refer to http://www.one-lab.net/ */

/* Data Handling Class */
#ifndef _IFE_H_
#define _IFE_H_

#include "config.h"
namespace ns {
	class ife {
		public:
			virtual int Fx1(bool* aArg, int* aReturn) = 0;
		};//interface ife
	}//namespace ns

#endif