/* This class framework is generated by Core Frame Builder. */
/* For more information, refer to http://www.one-lab.net/ */

/* Data Handling Class */
package javans;
 
import java.lang.*;
import java.text.*;
import java.util.*;
import net.onelab.*;
import net.onelab.JSONException;
import net.onelab.JSONObject;

public interface cls {
public Boolean FuncBool(Boolean aArgBool, net.onelab.Bytes aArgBytes, java.util.GregorianCalendar aArgDate, java.util.GregorianCalendar aArgDateTime, Double aArgDouble, Float aArgFloat, Integer aArgInt32, String aArgText, java.util.GregorianCalendar aArgTime, Integer aArgUInt32);
public net.onelab.Bytes FuncBytes(Boolean aArgBool, net.onelab.Bytes aArgBytes, java.util.GregorianCalendar aArgDate, java.util.GregorianCalendar aArgDateTime, Double aArgDouble, Float aArgFloat, Integer aArgInt32, String aArgText, java.util.GregorianCalendar aArgTime, Integer aArgUInt32);
public java.util.GregorianCalendar FuncDate(Boolean aArgBool, net.onelab.Bytes aArgBytes, java.util.GregorianCalendar aArgDate, java.util.GregorianCalendar aArgDateTime, Double aArgDouble, Float aArgFloat, Integer aArgInt32, String aArgText, java.util.GregorianCalendar aArgTime, Integer aArgUInt32);
public java.util.GregorianCalendar FuncDateTime(Boolean aArgBool, net.onelab.Bytes aArgBytes, java.util.GregorianCalendar aArgDate, java.util.GregorianCalendar aArgDateTime, Double aArgDouble, Float aArgFloat, Integer aArgInt32, String aArgText, java.util.GregorianCalendar aArgTime, Integer aArgUInt32);
public Double FuncDouble(Boolean aArgBool, net.onelab.Bytes aArgBytes, java.util.GregorianCalendar aArgDate, java.util.GregorianCalendar aArgDateTime, Double aArgDouble, Float aArgFloat, Integer aArgInt32, String aArgText, java.util.GregorianCalendar aArgTime, Integer aArgUInt32);
public Float FuncFloat(Boolean aArgBool, net.onelab.Bytes aArgBytes, java.util.GregorianCalendar aArgDate, java.util.GregorianCalendar aArgDateTime, Double aArgDouble, Float aArgFloat, Integer aArgInt32, String aArgText, java.util.GregorianCalendar aArgTime, Integer aArgUInt32);
public Integer FuncInt32(Boolean aArgBool, net.onelab.Bytes aArgBytes, java.util.GregorianCalendar aArgDate, java.util.GregorianCalendar aArgDateTime, Double aArgDouble, Float aArgFloat, Integer aArgInt32, String aArgText, java.util.GregorianCalendar aArgTime, Integer aArgUInt32);
public String FuncText(Boolean aArgBool, net.onelab.Bytes aArgBytes, java.util.GregorianCalendar aArgDate, java.util.GregorianCalendar aArgDateTime, Double aArgDouble, Float aArgFloat, Integer aArgInt32, String aArgText, java.util.GregorianCalendar aArgTime, Integer aArgUInt32);
public java.util.GregorianCalendar FuncTime(Boolean aArgBool, net.onelab.Bytes aArgBytes, java.util.GregorianCalendar aArgDate, java.util.GregorianCalendar aArgDateTime, Double aArgDouble, Float aArgFloat, Integer aArgInt32, String aArgText, java.util.GregorianCalendar aArgTime, Integer aArgUInt32);
public Integer FuncUInt32(Boolean aArgBool, net.onelab.Bytes aArgBytes, java.util.GregorianCalendar aArgDate, java.util.GregorianCalendar aArgDateTime, Double aArgDouble, Float aArgFloat, Integer aArgInt32, String aArgText, java.util.GregorianCalendar aArgTime, Integer aArgUInt32);
}//interface cls