/* This class framework is generated by Core Frame Builder. */
/* For more information, refer to http://www.one-lab.net/ */

/* Data Handling Class */
package javans;
 
import java.lang.*;
import java.text.*;
import java.util.*;
import net.onelab.*;
import net.onelab.JSONException;
import net.onelab.JSONObject;

public interface cls {
public Boolean FuncBool();
public net.onelab.Bytes FuncBytes();
public java.util.GregorianCalendar FuncDate();
public java.util.GregorianCalendar FuncDateTime();
public Double FuncDouble();
public Float FuncFloat();
public Integer FuncInt32();
public String FuncText();
public java.util.GregorianCalendar FuncTime();
public Integer FuncUInt32();
}//interface cls