/* This class framework is generated by Core Frame Builder. */
/* For more information, refer to http://www.one-lab.net/ */

/* Data Handling Class */
package javans;
 
import java.lang.*;
import java.text.*;
import java.util.*;
import net.onelab.*;
import net.onelab.JSONException;
import net.onelab.JSONObject;

public class cls implements Cloneable {
public enum MySize { mz1, mz2, mz3 }
static private SortedMap<javans.cls.MySize, String> cls_MySizeValues = new TreeMap<javans.cls.MySize, String>();
static public void set_MySizeValues() {
	if (!cls_MySizeValues.isEmpty()) return;
	cls_MySizeValues.put(javans.cls.MySize.mz1, "");
	cls_MySizeValues.put(javans.cls.MySize.mz2, "");
	cls_MySizeValues.put(javans.cls.MySize.mz3, "");
}
static public String get_MySizeValues(javans.cls.MySize key) {
	return cls_MySizeValues.get(key);
}

protected void clone_from(cls aValue) {
}

public Object clone() {
	cls oValue = new cls();
	oValue.clone_from(this);
	return oValue;
}

public boolean equals(Object oValue) {
	if (oValue == null) return false;
	if (this == oValue) return true;
	return true;
}
public cls() {
}

public javans.cls.MySize Func(javans.cls.MySize aArg) {
//function-begin : public javans.cls.MySize Func(javans.cls.MySize aArg) @ javans.cls
	net.onelab.log.info("javans.cls.Func(javans.cls.MySize aArg)", "[enter]");
	return javans.cls.MySize.values()[0];
//function-end
}

public void _invoke_(String entry, String input, String output) {
	if (false){}
	else if (entry.equals("Func")){
	}
}
}//class cls