/* This class framework is generated by Core Frame Builder. */
/* For more information, refer to http://www.one-lab.net/ */

/* Data Handling Class */
package javans;
 
import java.lang.*;
import java.text.*;
import java.util.*;
import net.onelab.*;
import net.onelab.JSONException;
import net.onelab.JSONObject;

public interface cls {
public int FuncBool(Boolean aArgBool, net.onelab.Bytes aArgBytes, java.util.GregorianCalendar aArgDate, java.util.GregorianCalendar aArgDateTime, Double aArgDouble, Float aArgFloat, Integer aArgInt32, String aArgText, java.util.GregorianCalendar aArgTime, Integer aArgUInt32, net.onelab.ReturnBoolean aReturn);
public int FuncBytes(Boolean aArgBool, net.onelab.Bytes aArgBytes, java.util.GregorianCalendar aArgDate, java.util.GregorianCalendar aArgDateTime, Double aArgDouble, Float aArgFloat, Integer aArgInt32, String aArgText, java.util.GregorianCalendar aArgTime, Integer aArgUInt32, net.onelab.Bytes aReturn);
public int FuncDate(Boolean aArgBool, net.onelab.Bytes aArgBytes, java.util.GregorianCalendar aArgDate, java.util.GregorianCalendar aArgDateTime, Double aArgDouble, Float aArgFloat, Integer aArgInt32, String aArgText, java.util.GregorianCalendar aArgTime, Integer aArgUInt32, net.onelab.ReturnDate aReturn);
public int FuncDateTime(Boolean aArgBool, net.onelab.Bytes aArgBytes, java.util.GregorianCalendar aArgDate, java.util.GregorianCalendar aArgDateTime, Double aArgDouble, Float aArgFloat, Integer aArgInt32, String aArgText, java.util.GregorianCalendar aArgTime, Integer aArgUInt32, net.onelab.ReturnDatetime aReturn);
public int FuncDouble(Boolean aArgBool, net.onelab.Bytes aArgBytes, java.util.GregorianCalendar aArgDate, java.util.GregorianCalendar aArgDateTime, Double aArgDouble, Float aArgFloat, Integer aArgInt32, String aArgText, java.util.GregorianCalendar aArgTime, Integer aArgUInt32, net.onelab.ReturnDouble aReturn);
public int FuncFloat(Boolean aArgBool, net.onelab.Bytes aArgBytes, java.util.GregorianCalendar aArgDate, java.util.GregorianCalendar aArgDateTime, Double aArgDouble, Float aArgFloat, Integer aArgInt32, String aArgText, java.util.GregorianCalendar aArgTime, Integer aArgUInt32, net.onelab.ReturnFloat aReturn);
public int FuncInt32(Boolean aArgBool, net.onelab.Bytes aArgBytes, java.util.GregorianCalendar aArgDate, java.util.GregorianCalendar aArgDateTime, Double aArgDouble, Float aArgFloat, Integer aArgInt32, String aArgText, java.util.GregorianCalendar aArgTime, Integer aArgUInt32, net.onelab.ReturnInt32 aReturn);
public int FuncText(Boolean aArgBool, net.onelab.Bytes aArgBytes, java.util.GregorianCalendar aArgDate, java.util.GregorianCalendar aArgDateTime, Double aArgDouble, Float aArgFloat, Integer aArgInt32, String aArgText, java.util.GregorianCalendar aArgTime, Integer aArgUInt32, net.onelab.ReturnText aReturn);
public int FuncTime(Boolean aArgBool, net.onelab.Bytes aArgBytes, java.util.GregorianCalendar aArgDate, java.util.GregorianCalendar aArgDateTime, Double aArgDouble, Float aArgFloat, Integer aArgInt32, String aArgText, java.util.GregorianCalendar aArgTime, Integer aArgUInt32, net.onelab.ReturnTime aReturn);
public int FuncUInt32(Boolean aArgBool, net.onelab.Bytes aArgBytes, java.util.GregorianCalendar aArgDate, java.util.GregorianCalendar aArgDateTime, Double aArgDouble, Float aArgFloat, Integer aArgInt32, String aArgText, java.util.GregorianCalendar aArgTime, Integer aArgUInt32, net.onelab.ReturnUInt32 aReturn);
}//interface cls