/* This class framework is generated by Core Frame Builder. */
/* For more information, refer to http://www.one-lab.net/ */

/* Data Handling Class */
#ifndef _CLS_H_
#define _CLS_H_

#include "config.h"
#include "values.h"
namespace qtns {
	class cls {
		public:
			virtual int FuncBool(bool* aArgBool, onelab::Bytes* aArgBytes, QDate* aArgDate, QDateTime* aArgDateTime, double* aArgDouble, float* aArgFloat, int* aArgInt32, QString* aArgText, QTime* aArgTime, unsigned int* aArgUInt32, bool* aReturn) = 0;
			virtual int FuncBytes(bool* aArgBool, onelab::Bytes* aArgBytes, QDate* aArgDate, QDateTime* aArgDateTime, double* aArgDouble, float* aArgFloat, int* aArgInt32, QString* aArgText, QTime* aArgTime, unsigned int* aArgUInt32, onelab::Bytes* aReturn) = 0;
			virtual int FuncDate(bool* aArgBool, onelab::Bytes* aArgBytes, QDate* aArgDate, QDateTime* aArgDateTime, double* aArgDouble, float* aArgFloat, int* aArgInt32, QString* aArgText, QTime* aArgTime, unsigned int* aArgUInt32, QDate* aReturn) = 0;
			virtual int FuncDateTime(bool* aArgBool, onelab::Bytes* aArgBytes, QDate* aArgDate, QDateTime* aArgDateTime, double* aArgDouble, float* aArgFloat, int* aArgInt32, QString* aArgText, QTime* aArgTime, unsigned int* aArgUInt32, QDateTime* aReturn) = 0;
			virtual int FuncDouble(bool* aArgBool, onelab::Bytes* aArgBytes, QDate* aArgDate, QDateTime* aArgDateTime, double* aArgDouble, float* aArgFloat, int* aArgInt32, QString* aArgText, QTime* aArgTime, unsigned int* aArgUInt32, double* aReturn) = 0;
			virtual int FuncFloat(bool* aArgBool, onelab::Bytes* aArgBytes, QDate* aArgDate, QDateTime* aArgDateTime, double* aArgDouble, float* aArgFloat, int* aArgInt32, QString* aArgText, QTime* aArgTime, unsigned int* aArgUInt32, float* aReturn) = 0;
			virtual int FuncInt32(bool* aArgBool, onelab::Bytes* aArgBytes, QDate* aArgDate, QDateTime* aArgDateTime, double* aArgDouble, float* aArgFloat, int* aArgInt32, QString* aArgText, QTime* aArgTime, unsigned int* aArgUInt32, int* aReturn) = 0;
			virtual int FuncText(bool* aArgBool, onelab::Bytes* aArgBytes, QDate* aArgDate, QDateTime* aArgDateTime, double* aArgDouble, float* aArgFloat, int* aArgInt32, QString* aArgText, QTime* aArgTime, unsigned int* aArgUInt32, QString* aReturn) = 0;
			virtual int FuncTime(bool* aArgBool, onelab::Bytes* aArgBytes, QDate* aArgDate, QDateTime* aArgDateTime, double* aArgDouble, float* aArgFloat, int* aArgInt32, QString* aArgText, QTime* aArgTime, unsigned int* aArgUInt32, QTime* aReturn) = 0;
			virtual int FuncUInt32(bool* aArgBool, onelab::Bytes* aArgBytes, QDate* aArgDate, QDateTime* aArgDateTime, double* aArgDouble, float* aArgFloat, int* aArgInt32, QString* aArgText, QTime* aArgTime, unsigned int* aArgUInt32, unsigned int* aReturn) = 0;
		public:
			void _invoke_(const QString& entry, const QString& input, QString& output);
		};//interface cls
	}//namespace qtns

#endif