/* This class framework is generated by Core Frame Builder. */
/* For more information, refer to http://www.one-lab.net/ */

/* Data Handling Class */
#ifndef _CLS_H_
#define _CLS_H_

#include "config.h"
#include "values.h"
namespace qtns {
	class cls {
		friend class clsList;

			rw_field(bool, PBool)

			rw_field(onelab::Bytes, PBytes)

			rw_field(QDate, PDate)

			rw_field(QDateTime, PDateTime)

			rw_field(double, PDouble)

			rw_field(float, PFloat)

			rw_field(int, PInt32)

			rw_field(QString, PText)

			rw_field(QTime, PTime)

			rw_field(unsigned int, PUInt32)

		public:
			static int field_count();
		protected:
			virtual int input_field(const QString& key, const QVariant& value, bool _set_value);
		private:
			int validate_field(const QString& key, const QVariant& value);
			int validate_field(int index, const QVariant& value);
			int input_field(int index, const QVariant& value, bool _set_value);
		public:
			virtual int to_json(QString& output);
			int from_json(const QString& output);
			int from_json(const QMap<QString, QVariant>& map);
		protected:
			inline bool compare_to(cls& aValue) const;
		public:
			inline void clone_from(cls& aValue);
			inline bool operator==(cls &aValue) const { return compare_to(aValue); }
			inline bool operator!=(cls &aValue) const { return !compare_to(aValue); }
			#ifdef _MSC_VER
				inline void operator=(cls &aValue) { clone_from(aValue); }
			#endif
		public:
			~cls();
			cls();
			cls(const bool& aPBool, const onelab::Bytes& aPBytes, const QDate& aPDate, const QDateTime& aPDateTime, const double& aPDouble, const float& aPFloat, const int& aPInt32, const QString& aPText, const QTime& aPTime, const unsigned int& aPUInt32);
		public:
			void _invoke_(const QString& entry, const QString& input, QString& output);
	};//class cls
	class clsList {
		private:
			inline bool compare_to(clsList& aValue) const;
		public:
			QList<cls> Items;
			inline bool operator==(clsList& aValue) const { return compare_to(aValue); }
			inline bool operator!=(clsList& aValue) const { return !compare_to(aValue); }
			int to_json(QString& output, const QString& tag = "cls");
			int from_json(const QString& input, const QString& tag = "cls");
	};//class clsList
}//namespace qtns

#endif