/* This class framework is generated by Core Frame Builder. */
/* For more information, refer to http://www.one-lab.net/ */

/* Data Handling Class */
using System;
using System.Text;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.IO;

namespace csns {
interface cls {
	//--------------------------------------------------------------------------------
	Boolean FuncBool();
	//--------------------------------------------------------------------------------
	onelab.Bytes FuncBytes();
	//--------------------------------------------------------------------------------
	DateTime FuncDate();
	//--------------------------------------------------------------------------------
	DateTime FuncDateTime();
	//--------------------------------------------------------------------------------
	Double FuncDouble();
	//--------------------------------------------------------------------------------
	Single FuncFloat();
	//--------------------------------------------------------------------------------
	Int32 FuncInt32();
	//--------------------------------------------------------------------------------
	String FuncText();
	//--------------------------------------------------------------------------------
	DateTime FuncTime();
	//--------------------------------------------------------------------------------
	UInt32 FuncUInt32();
	}//interface
}//namespace csns