/* This class framework is generated by Core Frame Builder. */
/* For more information, refer to http://www.one-lab.net/ */

/* Data Handling Class */
using System;
using System.Text;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.IO;

namespace ns {
public class cls3 : ns.cls2 {
	public cls3() {
	}

	public void _invoke_(String entry, String input, ref String output) {
		if (false){}
	}
}//class cls3
}//namespace ns