/* This class framework is generated by Core Frame Builder. */
/* For more information, refer to http://www.one-lab.net/ */

/* Data Handling Class */
using System;
using System.Text;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.IO;

namespace ns {
interface ife {
	//--------------------------------------------------------------------------------
	int Fx1(Boolean aArg, ref Int32 aReturn);
	}//interface
}//namespace ns