/* This class framework is generated by Core Frame Builder. */
/* For more information, refer to http://www.one-lab.net/ */

/* Data Handling Class */
#ifndef _CLS3_H_
#define _CLS3_H_

#include "config.h"
#include "ns/cls2.h"
namespace ns {
	class cls3 : public ns::cls2 {
		public:
			~cls3();
			cls3();
		public:
			void _invoke_(const QString& entry, const QString& input, QString& output);
	};//class cls3
}//namespace ns

#endif