/* This class framework is generated by Core Frame Builder. */
/* For more information, refer to http://www.one-lab.net/ */

/* Data Handling Class */
#include "cls3.h"
ns::cls3::~cls3() {
}

ns::cls3::cls3() {
}

void ns::cls3::_invoke_(const QString& entry, const QString& input, QString& output) {
	if (false){}
}