/* This class framework is generated by Core Frame Builder. */
/* For more information, refer to http://www.one-lab.net/ */

/* Data Handling Class */
#include "cls.h"
#include "log.h"
static QMap<qtns::cls::MySize, QString> cls_MySizeValues;

QString qtns::cls::get_MySizeValues(qtns::cls::MySize key) {
	return cls_MySizeValues[key];
}

void qtns::cls::set_MySizeValues() {
	if (!cls_MySizeValues.isEmpty()) return;
	cls_MySizeValues[qtns::cls::MySize::mz1] = "";
	cls_MySizeValues[qtns::cls::MySize::mz2] = "";
	cls_MySizeValues[qtns::cls::MySize::mz3] = "";
}

qtns::cls::~cls() {
}

qtns::cls::cls() {
}

int qtns::cls::Func(qtns::cls::MySize* aArg, qtns::cls::MySize* aReturn) {
//function-begin : int qtns::cls::Func(qtns::cls::MySize* aArg, qtns::cls::MySize* aReturn) @ qtns.cls
	onelab::log::info("qtns::cls::Func(qtns::cls::MySize* aArg)", "[enter]");
	return 0;
//function-end
}

void qtns::cls::_invoke_(const QString& entry, const QString& input, QString& output) {
	if (false){}
	else if (entry == "Func"){
	}
}