/* This class framework is generated by Core Frame Builder. */
/* For more information, refer to http://www.one-lab.net/ */

/* Data Handling Class */
#ifndef _CLS_H_
#define _CLS_H_

#include "config.h"
namespace qtns {
	class cls {
		public:
			enum MySize { mz1, mz2, mz3 };
			static void set_MySizeValues();
			static QString get_MySizeValues(qtns::cls::MySize key);
		public:
			virtual qtns::cls::MySize Func(qtns::cls::MySize* aArg);
		public:
			~cls();
			cls();
		public:
			void _invoke_(const QString& entry, const QString& input, QString& output);
	};//class cls
}//namespace qtns

#endif