/* This class framework is generated by Core Frame Builder. */
/* For more information, refer to http://www.one-lab.net/ */

/* Data Handling Class */
package javans;
 
import java.lang.*;
import java.text.*;
import java.util.*;
import net.onelab.*;
import net.onelab.JSONException;
import net.onelab.JSONObject;

public class cls implements Cloneable {
protected void clone_from(cls aValue) {
	setPBool(aValue.getPBool());
}

public Object clone() {
	cls oValue = new cls();
	oValue.clone_from(this);
	return oValue;
}

public boolean equals(Object oValue) {
	if (oValue == null) return false;
	if (this == oValue) return true;
	cls aValue = (cls)oValue;
	if (!mPBool.equals(aValue.getPBool())) return false;
	return true;
}
 
private Boolean mPBool = new Boolean(false);

public void setPBool(Boolean aPBool) {
	mPBool = aPBool;
}

public Boolean getPBool() {
	 return mPBool;
}

public cls() {
}

public cls(Boolean aPBool) {
	setPBool(aPBool);
}

public int FuncBool(net.onelab.ReturnBoolean aReturn) {
//function-begin : public int FuncBool(net.onelab.ReturnBoolean aReturn) @ javans.cls
	net.onelab.log.info("javans.cls.FuncBool()", "[enter]");
	return 0;
//function-end
}

public int FuncBytes(net.onelab.Bytes aReturn) {
//function-begin : public int FuncBytes(net.onelab.Bytes aReturn) @ javans.cls
	net.onelab.log.info("javans.cls.FuncBytes()", "[enter]");
	return 0;
//function-end
}

public int FuncDate(net.onelab.ReturnDate aReturn) {
//function-begin : public int FuncDate(net.onelab.ReturnDate aReturn) @ javans.cls
	net.onelab.log.info("javans.cls.FuncDate()", "[enter]");
	return 0;
//function-end
}

public int FuncDateTime(net.onelab.ReturnDatetime aReturn) {
//function-begin : public int FuncDateTime(net.onelab.ReturnDatetime aReturn) @ javans.cls
	net.onelab.log.info("javans.cls.FuncDateTime()", "[enter]");
	return 0;
//function-end
}

public int FuncDouble(net.onelab.ReturnDouble aReturn) {
//function-begin : public int FuncDouble(net.onelab.ReturnDouble aReturn) @ javans.cls
	net.onelab.log.info("javans.cls.FuncDouble()", "[enter]");
	return 0;
//function-end
}

public int FuncFloat(net.onelab.ReturnFloat aReturn) {
//function-begin : public int FuncFloat(net.onelab.ReturnFloat aReturn) @ javans.cls
	net.onelab.log.info("javans.cls.FuncFloat()", "[enter]");
	return 0;
//function-end
}

public int FuncInt32(net.onelab.ReturnInt32 aReturn) {
//function-begin : public int FuncInt32(net.onelab.ReturnInt32 aReturn) @ javans.cls
	net.onelab.log.info("javans.cls.FuncInt32()", "[enter]");
	return 0;
//function-end
}

public int FuncText(net.onelab.ReturnText aReturn) {
//function-begin : public int FuncText(net.onelab.ReturnText aReturn) @ javans.cls
	net.onelab.log.info("javans.cls.FuncText()", "[enter]");
	return 0;
//function-end
}

public int FuncTime(net.onelab.ReturnTime aReturn) {
//function-begin : public int FuncTime(net.onelab.ReturnTime aReturn) @ javans.cls
	net.onelab.log.info("javans.cls.FuncTime()", "[enter]");
	return 0;
//function-end
}

public int FuncUInt32(net.onelab.ReturnUInt32 aReturn) {
//function-begin : public int FuncUInt32(net.onelab.ReturnUInt32 aReturn) @ javans.cls
	net.onelab.log.info("javans.cls.FuncUInt32()", "[enter]");
	return 0;
//function-end
}

public void _invoke_(String entry, String input, String output) {
	if (false){}
	else if (entry.equals("FuncBool")){
	}
	else if (entry.equals("FuncBytes")){
	}
	else if (entry.equals("FuncDate")){
	}
	else if (entry.equals("FuncDateTime")){
	}
	else if (entry.equals("FuncDouble")){
	}
	else if (entry.equals("FuncFloat")){
	}
	else if (entry.equals("FuncInt32")){
	}
	else if (entry.equals("FuncText")){
	}
	else if (entry.equals("FuncTime")){
	}
	else if (entry.equals("FuncUInt32")){
	}
}
public static int field_count() {
	return 1;
}

private int validate_field(String key, Object value) throws ParseException {
	return input_field(key, value, false);
}

private int validate_field(int index, Object value) throws ParseException {
	return input_field(index, value, false);
}

public int input_field(String key, Object value, boolean _set_value) throws ParseException {
	int result = 0;
	if (key == null || key.isEmpty() || value == null) return 0;
	else if (key.equals("PBool")) {
		if (_set_value) {
			Boolean v = Boolean.valueOf(value.toString());
			mPBool = v;
		}
		result = 1;
	}
	return result;
}

private static final String field_keys[] = { "PBool",  };
private int input_field(int index, Object value, boolean _set_value) throws ParseException {
	if (index < 0 || index > (field_count()-1) || value == null) return 0;
	return input_field(field_keys[index], value, _set_value);
}

public int to_json(StringBuilder output) {
	if (output == null) output = new StringBuilder(); else output.setLength(0);
	output.append("{" + "\"PBool\"" + ":" + "\"" + mPBool.toString() + "\"" + "}");
	return 1;
}

public int from_json(String input) throws JSONException, ParseException {
	if (input == null || input.length() == 0) return 0;
	JSONObject json = new JSONObject(input);
	if (json.length() != field_count()) return 0;
	for(String key : json.keySet())
		if (validate_field(key, json.get(key)) == 0)
			return 0;
	for(String key : json.keySet())
		input_field(key, json.get(key), true);
	return 1;
}

public int to_xml(StringBuilder output, String rowTag) {
	if (rowTag == null || rowTag.length() < 1) return 0;
	if (output == null) output = new StringBuilder(); else output.setLength(0);
	output.append("<" + rowTag + ">" + "<PBool>" + mPBool.toString().replace("<", "&lt;").replace(">", "&gt;") + "</PBool>" + "</" + rowTag + ">");
	return 1;
}

public int from_xml(String input, String rowTag) throws JSONException, ParseException {
	if (input == null || input.length() == 0 || rowTag == null || rowTag.length() == 0) return 0;
	JSONObject json = XML.toJSONObject(input);
	if (!json.has(rowTag)) return 0;
	return from_json(json.get(rowTag).toString());
}

public int to_sv(StringBuilder output, String spliter) {
	if (spliter == null || spliter.length() == 0) return 0;
	if (output == null) output = new StringBuilder(); else output.setLength(0);
	java.util.List<String> list = new ArrayList<String>();
	list.add(mPBool.toString());

	output.append(net.onelab.Text.join(spliter, list));
	return 1;
}

public int from_sv(String input, String spliter) throws ParseException {
	if (input == null || input.length() == 0 || spliter == null || spliter.length() == 0) return 0;
	String[] list = input.split(spliter);
	if (list.length != field_count()) return 0;
	int index = 0;
	for(String item : list)
		if (validate_field(index++, item) == 0)
			return 0;
	index = 0;
	for(String item : list)
		input_field(index++, item, true);
	return 1;
}

}//class cls