/* This class framework is generated by Core Frame Builder. */
/* For more information, refer to http://www.one-lab.net/ */

/* Data Handling Class */
#ifndef _CLS_H_
#define _CLS_H_

#include "config.h"
#include "values.h"
namespace qtns {
	class cls {
		public:
			virtual int FuncBool(bool* aReturn) = 0;
			virtual int FuncBytes(onelab::Bytes* aReturn) = 0;
			virtual int FuncDate(QDate* aReturn) = 0;
			virtual int FuncDateTime(QDateTime* aReturn) = 0;
			virtual int FuncDouble(double* aReturn) = 0;
			virtual int FuncFloat(float* aReturn) = 0;
			virtual int FuncInt32(int* aReturn) = 0;
			virtual int FuncText(QString* aReturn) = 0;
			virtual int FuncTime(QTime* aReturn) = 0;
			virtual int FuncUInt32(unsigned int* aReturn) = 0;
		public:
			void _invoke_(const QString& entry, const QString& input, QString& output);
		};//interface cls
	}//namespace qtns

#endif