/* This class framework is generated by Core Frame Builder. */
/* For more information, refer to http://www.one-lab.net/ */

/* Data Handling Class */
using System;
using System.Text;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.IO;

namespace csns {
interface cls {
	//--------------------------------------------------------------------------------
	Boolean FuncBool(Boolean aArgBool, onelab.Bytes aArgBytes, DateTime aArgDate, DateTime aArgDateTime, Double aArgDouble, Single aArgFloat, Int32 aArgInt32, String aArgText, DateTime aArgTime, UInt32 aArgUInt32);
	//--------------------------------------------------------------------------------
	onelab.Bytes FuncBytes(Boolean aArgBool, onelab.Bytes aArgBytes, DateTime aArgDate, DateTime aArgDateTime, Double aArgDouble, Single aArgFloat, Int32 aArgInt32, String aArgText, DateTime aArgTime, UInt32 aArgUInt32);
	//--------------------------------------------------------------------------------
	DateTime FuncDate(Boolean aArgBool, onelab.Bytes aArgBytes, DateTime aArgDate, DateTime aArgDateTime, Double aArgDouble, Single aArgFloat, Int32 aArgInt32, String aArgText, DateTime aArgTime, UInt32 aArgUInt32);
	//--------------------------------------------------------------------------------
	DateTime FuncDateTime(Boolean aArgBool, onelab.Bytes aArgBytes, DateTime aArgDate, DateTime aArgDateTime, Double aArgDouble, Single aArgFloat, Int32 aArgInt32, String aArgText, DateTime aArgTime, UInt32 aArgUInt32);
	//--------------------------------------------------------------------------------
	Double FuncDouble(Boolean aArgBool, onelab.Bytes aArgBytes, DateTime aArgDate, DateTime aArgDateTime, Double aArgDouble, Single aArgFloat, Int32 aArgInt32, String aArgText, DateTime aArgTime, UInt32 aArgUInt32);
	//--------------------------------------------------------------------------------
	Single FuncFloat(Boolean aArgBool, onelab.Bytes aArgBytes, DateTime aArgDate, DateTime aArgDateTime, Double aArgDouble, Single aArgFloat, Int32 aArgInt32, String aArgText, DateTime aArgTime, UInt32 aArgUInt32);
	//--------------------------------------------------------------------------------
	Int32 FuncInt32(Boolean aArgBool, onelab.Bytes aArgBytes, DateTime aArgDate, DateTime aArgDateTime, Double aArgDouble, Single aArgFloat, Int32 aArgInt32, String aArgText, DateTime aArgTime, UInt32 aArgUInt32);
	//--------------------------------------------------------------------------------
	String FuncText(Boolean aArgBool, onelab.Bytes aArgBytes, DateTime aArgDate, DateTime aArgDateTime, Double aArgDouble, Single aArgFloat, Int32 aArgInt32, String aArgText, DateTime aArgTime, UInt32 aArgUInt32);
	//--------------------------------------------------------------------------------
	DateTime FuncTime(Boolean aArgBool, onelab.Bytes aArgBytes, DateTime aArgDate, DateTime aArgDateTime, Double aArgDouble, Single aArgFloat, Int32 aArgInt32, String aArgText, DateTime aArgTime, UInt32 aArgUInt32);
	//--------------------------------------------------------------------------------
	UInt32 FuncUInt32(Boolean aArgBool, onelab.Bytes aArgBytes, DateTime aArgDate, DateTime aArgDateTime, Double aArgDouble, Single aArgFloat, Int32 aArgInt32, String aArgText, DateTime aArgTime, UInt32 aArgUInt32);
	}//interface
}//namespace csns