/* This class framework is generated by Core Frame Builder. */
/* For more information, refer to http://www.one-lab.net/ */

/* Data Handling Class */
package javans;
 
import java.lang.*;
import java.text.*;
import java.util.*;
import net.onelab.*;
import net.onelab.JSONException;
import net.onelab.JSONObject;

public interface cls {
public int FuncBool(net.onelab.ReturnBoolean aReturn);
public int FuncBytes(net.onelab.Bytes aReturn);
public int FuncDate(net.onelab.ReturnDate aReturn);
public int FuncDateTime(net.onelab.ReturnDatetime aReturn);
public int FuncDouble(net.onelab.ReturnDouble aReturn);
public int FuncFloat(net.onelab.ReturnFloat aReturn);
public int FuncInt32(net.onelab.ReturnInt32 aReturn);
public int FuncText(net.onelab.ReturnText aReturn);
public int FuncTime(net.onelab.ReturnTime aReturn);
public int FuncUInt32(net.onelab.ReturnUInt32 aReturn);
}//interface cls