/* This class framework is generated by Core Frame Builder. */
/* For more information, refer to http://www.one-lab.net/ */

/* Data Handling Class */
using System;
using System.Text;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.IO;

namespace csns {
interface cls {
	//--------------------------------------------------------------------------------
	int FuncBool(Boolean aArgBool, onelab.Bytes aArgBytes, DateTime aArgDate, DateTime aArgDateTime, Double aArgDouble, Single aArgFloat, Int32 aArgInt32, String aArgText, DateTime aArgTime, UInt32 aArgUInt32, ref Boolean aReturn);
	//--------------------------------------------------------------------------------
	int FuncBytes(Boolean aArgBool, onelab.Bytes aArgBytes, DateTime aArgDate, DateTime aArgDateTime, Double aArgDouble, Single aArgFloat, Int32 aArgInt32, String aArgText, DateTime aArgTime, UInt32 aArgUInt32, ref onelab.Bytes aReturn);
	//--------------------------------------------------------------------------------
	int FuncDate(Boolean aArgBool, onelab.Bytes aArgBytes, DateTime aArgDate, DateTime aArgDateTime, Double aArgDouble, Single aArgFloat, Int32 aArgInt32, String aArgText, DateTime aArgTime, UInt32 aArgUInt32, ref DateTime aReturn);
	//--------------------------------------------------------------------------------
	int FuncDateTime(Boolean aArgBool, onelab.Bytes aArgBytes, DateTime aArgDate, DateTime aArgDateTime, Double aArgDouble, Single aArgFloat, Int32 aArgInt32, String aArgText, DateTime aArgTime, UInt32 aArgUInt32, ref DateTime aReturn);
	//--------------------------------------------------------------------------------
	int FuncDouble(Boolean aArgBool, onelab.Bytes aArgBytes, DateTime aArgDate, DateTime aArgDateTime, Double aArgDouble, Single aArgFloat, Int32 aArgInt32, String aArgText, DateTime aArgTime, UInt32 aArgUInt32, ref Double aReturn);
	//--------------------------------------------------------------------------------
	int FuncFloat(Boolean aArgBool, onelab.Bytes aArgBytes, DateTime aArgDate, DateTime aArgDateTime, Double aArgDouble, Single aArgFloat, Int32 aArgInt32, String aArgText, DateTime aArgTime, UInt32 aArgUInt32, ref Single aReturn);
	//--------------------------------------------------------------------------------
	int FuncInt32(Boolean aArgBool, onelab.Bytes aArgBytes, DateTime aArgDate, DateTime aArgDateTime, Double aArgDouble, Single aArgFloat, Int32 aArgInt32, String aArgText, DateTime aArgTime, UInt32 aArgUInt32, ref Int32 aReturn);
	//--------------------------------------------------------------------------------
	int FuncText(Boolean aArgBool, onelab.Bytes aArgBytes, DateTime aArgDate, DateTime aArgDateTime, Double aArgDouble, Single aArgFloat, Int32 aArgInt32, String aArgText, DateTime aArgTime, UInt32 aArgUInt32, ref String aReturn);
	//--------------------------------------------------------------------------------
	int FuncTime(Boolean aArgBool, onelab.Bytes aArgBytes, DateTime aArgDate, DateTime aArgDateTime, Double aArgDouble, Single aArgFloat, Int32 aArgInt32, String aArgText, DateTime aArgTime, UInt32 aArgUInt32, ref DateTime aReturn);
	//--------------------------------------------------------------------------------
	int FuncUInt32(Boolean aArgBool, onelab.Bytes aArgBytes, DateTime aArgDate, DateTime aArgDateTime, Double aArgDouble, Single aArgFloat, Int32 aArgInt32, String aArgText, DateTime aArgTime, UInt32 aArgUInt32, ref UInt32 aReturn);
	}//interface
}//namespace csns